version: "3.8"

services:
    mysql_db:
        image: mariadb
        container_name: ${APP_NAME}-mysql
        command: --lower_case_table_names=2
        volumes:
            - wpmysql:/var/lib/mysql:delegated
        env_file: ./docker/.env
        restart: always
        ports:
            - '3306:3306'

    wordpress:
        build:
            context: ./docker
            dockerfile: Dockerfile
        image: wordpress:5.7.1-apache-ssl
        container_name: ${APP_NAME}-wordpress
        volumes:
            - .:/var/www/html:rw,cached
        extra_hosts:
            - "wpssl.net:172.17.0.1"
        depends_on:
            - mysql_db
        restart: always
        env_file: ./docker/.env
        environment:
            WORDPRESS_DB_HOST: mysql_db
        ports:
            - 8080:80
            - 443:443

volumes:
    wpmysql: